using System.ComponentModel;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace TG_Fitz.ReportService.Models {
    public static class ReportGenerator {
        public static string GeneratePdf(ReportMessage message) {

            var fileName = $"Report_{message.ChatId}_{DateTime.UtcNow:yyyyMMddHHmmss}.pdf";
            Directory.CreateDirectory("Reports"); 

            var outputPath = Path.Combine("Reports",fileName);
            
            Document.Create(container => {
                container.Page(page => {
                    page.Margin(30);
                    page.Header().Text("Loan Calculation Report").SemiBold().FontSize(20).FontColor(Colors.Blue.Medium);
                    page.Content().PaddingVertical(10).Column(col => {
                        col.Item().Text($"📅 Date: {message.Timestamp:yyyy-MM-dd HH:mm:ss}");
                        col.Item().Text($"🏢 Company: {message.CompanyName}");
                        col.Item().Text($"💰 Loan Amount: {message.LoanAmount:C}");
                        col.Item().Text($"📊 Total Interest: {message.TotalInterest:C}");
                        col.Item().Text($"💵 Total Payment: {message.TotalPayment:C}");
                    });
                    page.Footer().AlignCenter().Text(txt => {
                        txt.Span("Generated by TG Fitz Bot · ");
                        txt.Span(DateTime.UtcNow.ToString("yyyy-MM-dd HH:mm:ss"));
                    });
                });
            }).GeneratePdf(outputPath);
            return outputPath;
        }
    }
}
